language: cpp

compiler: gcc

before_script:
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-5; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - sudo apt-get install libboost-filesystem1.55-dev libboost-program-options1.55-dev
  - sudo apt-get install -qq cmake
  - sudo apt-get install -qq libgtkmm-3.0-dev
  - cmake -DWITH_QT=OFF -DWITH_GTK=OFF .

script: 
  - make

notifications:
  on_success: change
  on_failure: always